version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - logcheck
  settings:
    custom:
      logcheck:
        type: "module"
        description: Checks Go logging calls for Kubernetes logging conventions.
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
