/*
Copyright 2026 Michael Zalud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"os"
	"path/filepath"

	authorizationv1 "k8s.io/api/authorization/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// The shipped ClusterRole is generated from +kubebuilder:rbac markers, but the markers are
// hand-written and the calls are somewhere else entirely, so the two drift silently. Nothing else in
// the suite can catch it: the kubeactions tests run against a fake client, which has no authorizer,
// and the e2e suite never drives a drain against a budget-protected workload.
//
// That drift already shipped once. OD-38 added a Delete fall-back for a pod whose PodDisruptionBudget
// refused eviction, and no marker granted `delete` on pods -- so the fall-back was a 403 and the
// drain aborted on precisely the budget the change existed to override. Unit tests passed, because a
// fake client authorizes everything.
//
// So this asks the real authorizer, against the real generated role: for each call the executor makes
// against workloads it does not own, is the shipped role allowed to make it. The list below is the
// contract -- a new API call in the executor path belongs here, next to the call site that needs it.
var executorGrants = []struct {
	what        string
	group       string
	resource    string
	subresource string
	verb        string
}{
	// Drain: enumerate pods on the node, then evict each one.
	{"drain enumerates pods", "", "pods", "", "list"},
	{"drain evicts a pod", "", "pods", "eviction", "create"},
	// OD-38: the fall-back when a PodDisruptionBudget refuses the eviction
	// (internal/kubeactions.Runner.evictPodsOnNode).
	{"drain deletes a pod whose budget refused eviction", "", "pods", "", "delete"},
	// Cordon marks the node unschedulable before the drain.
	{"cordon patches a node", "", "nodes", "", "patch"},
	// ScaleWorkload writes spec.replicas on the workload itself rather than the scale subresource.
	{"scale patches a Deployment", "apps", "deployments", "", "patch"},
	{"scale patches a StatefulSet", "apps", "statefulsets", "", "patch"},
	{"scale resolves a ReplicaSet owner", "apps", "replicasets", "", "get"},
	// AgentShutdown writes the node's key into the projected signal Secret, and clears it on
	// revocation (NA-3).
	{"signal creates the projected Secret", "", "secrets", "", "create"},
	{"signal updates the projected Secret", "", "secrets", "", "update"},
	// Execution progress is recorded as Events on the acting objects.
	{"execution records an Event", "", "events", "", "create"},
}

var _ = Describe("The shipped ClusterRole", func() {
	const subject = "nut-operator-executor-rbac-subject"

	BeforeEach(func() {
		raw, err := os.ReadFile(filepath.Join("..", "..", "config", "rbac", "role.yaml"))
		Expect(err).NotTo(HaveOccurred(), "config/rbac/role.yaml must exist; it is generated by `make manifests`")

		role := &rbacv1.ClusterRole{}
		Expect(yaml.Unmarshal(raw, role)).To(Succeed())
		Expect(role.Rules).NotTo(BeEmpty(), "decoded an empty ClusterRole; this test would pass vacuously")
		role.ObjectMeta = metav1.ObjectMeta{Name: "nut-operator-executor-rbac-role"}

		binding := &rbacv1.ClusterRoleBinding{
			ObjectMeta: metav1.ObjectMeta{Name: "nut-operator-executor-rbac-binding"},
			RoleRef:    rbacv1.RoleRef{APIGroup: rbacv1.GroupName, Kind: "ClusterRole", Name: role.Name},
			Subjects:   []rbacv1.Subject{{Kind: rbacv1.UserKind, APIGroup: rbacv1.GroupName, Name: subject}},
		}

		_ = k8sClient.Delete(ctx, role)
		_ = k8sClient.Delete(ctx, binding)
		Expect(k8sClient.Create(ctx, role)).To(Succeed())
		Expect(k8sClient.Create(ctx, binding)).To(Succeed())
	})

	It("refuses a subject it has not been bound to, so an allowed answer means something", func() {
		review := &authorizationv1.SubjectAccessReview{
			Spec: authorizationv1.SubjectAccessReviewSpec{
				User: "nut-operator-executor-rbac-unbound",
				ResourceAttributes: &authorizationv1.ResourceAttributes{
					Resource: "pods", Verb: "delete",
				},
			},
		}
		Expect(k8sClient.Create(ctx, review)).To(Succeed())
		Expect(review.Status.Allowed).To(BeFalse(),
			"an unbound user was allowed to delete pods, so this suite cannot distinguish a granted verb from an ungranted one")
	})

	for _, grant := range executorGrants {
		It("permits the call where "+grant.what, func() {
			review := &authorizationv1.SubjectAccessReview{
				Spec: authorizationv1.SubjectAccessReviewSpec{
					User: subject,
					ResourceAttributes: &authorizationv1.ResourceAttributes{
						Group:       grant.group,
						Resource:    grant.resource,
						Subresource: grant.subresource,
						Verb:        grant.verb,
					},
				},
			}
			Expect(k8sClient.Create(ctx, review)).To(Succeed())
			Expect(review.Status.Allowed).To(BeTrue(),
				"the generated ClusterRole does not permit %s %s/%s -- add the verb to the +kubebuilder:rbac marker at the call site and re-run `make manifests`",
				grant.verb, grant.resource, grant.subresource)
		})
	}
})
