# This rule is not used by the project nut-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants explicit administrative permissions over power.zalud.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nut-operator
    app.kubernetes.io/managed-by: kustomize
  name: nutserver-admin-role
rules:
- apiGroups:
  - power.zalud.io
  resources:
  - nutservers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.zalud.io
  resources:
  - nutservers/status
  verbs:
  - get
