---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.zalud.io
  resources:
  - nodepoweragents
  - nutservers
  - pducapabilityprofiles
  - powerinfrastructures
  - powerinventoryedges
  - powerinventorynodes
  - powermanagementclusters
  - shutdownflows
  - upscapabilityprobes
  - upscapabilityprofiles
  - upsdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.zalud.io
  resources:
  - nodepoweragents/finalizers
  - nutservers/finalizers
  - pducapabilityprofiles/finalizers
  - powerinfrastructures/finalizers
  - powerinventoryedges/finalizers
  - powerinventorynodes/finalizers
  - powermanagementclusters/finalizers
  - shutdownflows/finalizers
  - upscapabilityprobes/finalizers
  - upscapabilityprofiles/finalizers
  - upsdevices/finalizers
  verbs:
  - update
- apiGroups:
  - power.zalud.io
  resources:
  - nodepoweragents/status
  - nutservers/status
  - pducapabilityprofiles/status
  - powerinfrastructures/status
  - powerinventoryedges/status
  - powerinventorynodes/status
  - powermanagementclusters/status
  - shutdownflows/status
  - upscapabilityprobes/status
  - upscapabilityprofiles/status
  - upsdevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.zalud.io
  resources:
  - shutdownhooks
  verbs:
  - get
  - list
  - watch
