---
## Append samples of your project ##
resources:
  - power_v1alpha1_powermanagementcluster.yaml
  - power_v1alpha1_upsdevice.yaml
  - power_v1alpha1_nutserver.yaml
  - power_v1alpha1_nodepoweragent.yaml
  - power_v1alpha1_shutdownflow.yaml
  - power_v1alpha1_powerinfrastructure.yaml
  - power_v1alpha1_upscapabilityprofile.yaml
  - power_v1alpha1_pducapabilityprofile.yaml
  - power_v1alpha1_powerinventoryedge.yaml
  - power_v1alpha1_powerinventorynode.yaml
  - power_v1alpha1_upscapabilityprobe.yaml
  - power_v1alpha1_shutdownhook.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
