//go:build !ignore_autogenerated

/*
Copyright 2026 Michael Zalud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbortPolicySpec) DeepCopyInto(out *AbortPolicySpec) {
	*out = *in
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbortPolicySpec.
func (in *AbortPolicySpec) DeepCopy() *AbortPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AbortPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentShutdownSpec) DeepCopyInto(out *AgentShutdownSpec) {
	*out = *in
	if in.SignalTTL != nil {
		in, out := &in.SignalTTL, &out.SignalTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RequireFreshTelemetry != nil {
		in, out := &in.RequireFreshTelemetry, &out.RequireFreshTelemetry
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentShutdownSpec.
func (in *AgentShutdownSpec) DeepCopy() *AgentShutdownSpec {
	if in == nil {
		return nil
	}
	out := new(AgentShutdownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRetentionSpec) DeepCopyInto(out *AuditRetentionSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRetentionSpec.
func (in *AuditRetentionSpec) DeepCopy() *AuditRetentionSpec {
	if in == nil {
		return nil
	}
	out := new(AuditRetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditSpoolSpec) DeepCopyInto(out *AuditSpoolSpec) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditSpoolSpec.
func (in *AuditSpoolSpec) DeepCopy() *AuditSpoolSpec {
	if in == nil {
		return nil
	}
	out := new(AuditSpoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockedNodeReleaseStatus) DeepCopyInto(out *BlockedNodeReleaseStatus) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockedNodeReleaseStatus.
func (in *BlockedNodeReleaseStatus) DeepCopy() *BlockedNodeReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(BlockedNodeReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGStorageSpec) DeepCopyInto(out *CNPGStorageSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.AppCredentialSecretRef != nil {
		in, out := &in.AppCredentialSecretRef, &out.AppCredentialSecretRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGStorageSpec.
func (in *CNPGStorageSpec) DeepCopy() *CNPGStorageSpec {
	if in == nil {
		return nil
	}
	out := new(CNPGStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityQuirk) DeepCopyInto(out *CapabilityQuirk) {
	*out = *in
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(CapabilityQuirkFirmware)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityQuirk.
func (in *CapabilityQuirk) DeepCopy() *CapabilityQuirk {
	if in == nil {
		return nil
	}
	out := new(CapabilityQuirk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityQuirkFirmware) DeepCopyInto(out *CapabilityQuirkFirmware) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityQuirkFirmware.
func (in *CapabilityQuirkFirmware) DeepCopy() *CapabilityQuirkFirmware {
	if in == nil {
		return nil
	}
	out := new(CapabilityQuirkFirmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShutdownStep) DeepCopyInto(out *CompiledShutdownStep) {
	*out = *in
	if in.ShutdownTier != nil {
		in, out := &in.ShutdownTier, &out.ShutdownTier
		*out = new(int32)
		**out = **in
	}
	if in.CumulativeDuration != nil {
		in, out := &in.CumulativeDuration, &out.CumulativeDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShutdownStep.
func (in *CompiledShutdownStep) DeepCopy() *CompiledShutdownStep {
	if in == nil {
		return nil
	}
	out := new(CompiledShutdownStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShutdownWave) DeepCopyInto(out *CompiledShutdownWave) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(int32)
		**out = **in
	}
	if in.ShutdownTier != nil {
		in, out := &in.ShutdownTier, &out.ShutdownTier
		*out = new(int32)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CumulativeDuration != nil {
		in, out := &in.CumulativeDuration, &out.CumulativeDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShutdownWave.
func (in *CompiledShutdownWave) DeepCopy() *CompiledShutdownWave {
	if in == nil {
		return nil
	}
	out := new(CompiledShutdownWave)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPostgresStorageSpec) DeepCopyInto(out *ExternalPostgresStorageSpec) {
	*out = *in
	out.DSNSecretKeyRef = in.DSNSecretKeyRef
	if in.RequireTLS != nil {
		in, out := &in.RequireTLS, &out.RequireTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPostgresStorageSpec.
func (in *ExternalPostgresStorageSpec) DeepCopy() *ExternalPostgresStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalPostgresStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowSafetySpec) DeepCopyInto(out *FlowSafetySpec) {
	*out = *in
	if in.RequireManualApproval != nil {
		in, out := &in.RequireManualApproval, &out.RequireManualApproval
		*out = new(bool)
		**out = **in
	}
	if in.MaxEstimatedDuration != nil {
		in, out := &in.MaxEstimatedDuration, &out.MaxEstimatedDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AllowUnidentifiedDevices != nil {
		in, out := &in.AllowUnidentifiedDevices, &out.AllowUnidentifiedDevices
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowSafetySpec.
func (in *FlowSafetySpec) DeepCopy() *FlowSafetySpec {
	if in == nil {
		return nil
	}
	out := new(FlowSafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageReference) DeepCopyInto(out *ImageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReference.
func (in *ImageReference) DeepCopy() *ImageReference {
	if in == nil {
		return nil
	}
	out := new(ImageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResourceStatus) DeepCopyInto(out *ManagedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResourceStatus.
func (in *ManagedResourceStatus) DeepCopy() *ManagedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTAuthSpec) DeepCopyInto(out *NUTAuthSpec) {
	*out = *in
	if in.ExistingSecretRef != nil {
		in, out := &in.ExistingSecretRef, &out.ExistingSecretRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.PerNodeUsers != nil {
		in, out := &in.PerNodeUsers, &out.PerNodeUsers
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTAuthSpec.
func (in *NUTAuthSpec) DeepCopy() *NUTAuthSpec {
	if in == nil {
		return nil
	}
	out := new(NUTAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServer) DeepCopyInto(out *NUTServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServer.
func (in *NUTServer) DeepCopy() *NUTServer {
	if in == nil {
		return nil
	}
	out := new(NUTServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NUTServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerConfigSpec) DeepCopyInto(out *NUTServerConfigSpec) {
	*out = *in
	if in.MaxStartDelay != nil {
		in, out := &in.MaxStartDelay, &out.MaxStartDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerConfigSpec.
func (in *NUTServerConfigSpec) DeepCopy() *NUTServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NUTServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerList) DeepCopyInto(out *NUTServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NUTServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerList.
func (in *NUTServerList) DeepCopy() *NUTServerList {
	if in == nil {
		return nil
	}
	out := new(NUTServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NUTServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerSpec) DeepCopyInto(out *NUTServerSpec) {
	*out = *in
	if in.ManagementClusterRef != nil {
		in, out := &in.ManagementClusterRef, &out.ManagementClusterRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	if in.DeviceRefs != nil {
		in, out := &in.DeviceRefs, &out.DeviceRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
	if in.DeviceSelector != nil {
		in, out := &in.DeviceSelector, &out.DeviceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Image = in.Image
	in.Placement.DeepCopyInto(&out.Placement)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Service.DeepCopyInto(&out.Service)
	in.Auth.DeepCopyInto(&out.Auth)
	in.TLS.DeepCopyInto(&out.TLS)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerSpec.
func (in *NUTServerSpec) DeepCopy() *NUTServerSpec {
	if in == nil {
		return nil
	}
	out := new(NUTServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerStatus) DeepCopyInto(out *NUTServerStatus) {
	*out = *in
	if in.SelectedDevices != nil {
		in, out := &in.SelectedDevices, &out.SelectedDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceEndpoints != nil {
		in, out := &in.ServiceEndpoints, &out.ServiceEndpoints
		*out = make([]ServiceEndpointStatus, len(*in))
		copy(*out, *in)
	}
	if in.UpstreamNUT != nil {
		in, out := &in.UpstreamNUT, &out.UpstreamNUT
		*out = make([]NUTUpstreamStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerStatus.
func (in *NUTServerStatus) DeepCopy() *NUTServerStatus {
	if in == nil {
		return nil
	}
	out := new(NUTServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServiceSpec) DeepCopyInto(out *NUTServiceSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServiceSpec.
func (in *NUTServiceSpec) DeepCopy() *NUTServiceSpec {
	if in == nil {
		return nil
	}
	out := new(NUTServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTTLSSpec) DeepCopyInto(out *NUTTLSSpec) {
	*out = *in
	if in.ServerCertificateRef != nil {
		in, out := &in.ServerCertificateRef, &out.ServerCertificateRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.ServerCARef != nil {
		in, out := &in.ServerCARef, &out.ServerCARef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.ClientCARef != nil {
		in, out := &in.ClientCARef, &out.ClientCARef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.VerifyClientCertificates != nil {
		in, out := &in.VerifyClientCertificates, &out.VerifyClientCertificates
		*out = new(bool)
		**out = **in
	}
	if in.DisableWeakProtocols != nil {
		in, out := &in.DisableWeakProtocols, &out.DisableWeakProtocols
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTTLSSpec.
func (in *NUTTLSSpec) DeepCopy() *NUTTLSSpec {
	if in == nil {
		return nil
	}
	out := new(NUTTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTUpstreamStatus) DeepCopyInto(out *NUTUpstreamStatus) {
	*out = *in
	if in.Reachable != nil {
		in, out := &in.Reachable, &out.Reachable
		*out = new(bool)
		**out = **in
	}
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTUpstreamStatus.
func (in *NUTUpstreamStatus) DeepCopy() *NUTUpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(NUTUpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedNameReference) DeepCopyInto(out *NamespacedNameReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedNameReference.
func (in *NamespacedNameReference) DeepCopy() *NamespacedNameReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedNameReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgent) DeepCopyInto(out *NodePowerAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgent.
func (in *NodePowerAgent) DeepCopy() *NodePowerAgent {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePowerAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentImages) DeepCopyInto(out *NodePowerAgentImages) {
	*out = *in
	out.Upsmon = in.Upsmon
	out.Actuator = in.Actuator
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentImages.
func (in *NodePowerAgentImages) DeepCopy() *NodePowerAgentImages {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentList) DeepCopyInto(out *NodePowerAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePowerAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentList.
func (in *NodePowerAgentList) DeepCopy() *NodePowerAgentList {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePowerAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentNodeStatus) DeepCopyInto(out *NodePowerAgentNodeStatus) {
	*out = *in
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentNodeStatus.
func (in *NodePowerAgentNodeStatus) DeepCopy() *NodePowerAgentNodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentResources) DeepCopyInto(out *NodePowerAgentResources) {
	*out = *in
	in.Upsmon.DeepCopyInto(&out.Upsmon)
	in.Actuator.DeepCopyInto(&out.Actuator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentResources.
func (in *NodePowerAgentResources) DeepCopy() *NodePowerAgentResources {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentSpec) DeepCopyInto(out *NodePowerAgentSpec) {
	*out = *in
	if in.ManagementClusterRef != nil {
		in, out := &in.ManagementClusterRef, &out.ManagementClusterRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	if in.NUTServerRefs != nil {
		in, out := &in.NUTServerRefs, &out.NUTServerRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ShutdownFlowRef != nil {
		in, out := &in.ShutdownFlowRef, &out.ShutdownFlowRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	out.Images = in.Images
	in.Placement.DeepCopyInto(&out.Placement)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Upsmon.DeepCopyInto(&out.Upsmon)
	in.Shutdown.DeepCopyInto(&out.Shutdown)
	in.Hardening.DeepCopyInto(&out.Hardening)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentSpec.
func (in *NodePowerAgentSpec) DeepCopy() *NodePowerAgentSpec {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentStatus) DeepCopyInto(out *NodePowerAgentStatus) {
	*out = *in
	if in.SelectedNodes != nil {
		in, out := &in.SelectedNodes, &out.SelectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make([]NodePowerAgentNodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentStatus.
func (in *NodePowerAgentStatus) DeepCopy() *NodePowerAgentStatus {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectNameReference) DeepCopyInto(out *ObjectNameReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectNameReference.
func (in *ObjectNameReference) DeepCopy() *ObjectNameReference {
	if in == nil {
		return nil
	}
	out := new(ObjectNameReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandNamespaceSpec) DeepCopyInto(out *OperandNamespaceSpec) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandNamespaceSpec.
func (in *OperandNamespaceSpec) DeepCopy() *OperandNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(OperandNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityOutletSpec) DeepCopyInto(out *PDUCapabilityOutletSpec) {
	*out = *in
	if in.Switchable != nil {
		in, out := &in.Switchable, &out.Switchable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityOutletSpec.
func (in *PDUCapabilityOutletSpec) DeepCopy() *PDUCapabilityOutletSpec {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityOutletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityProfile) DeepCopyInto(out *PDUCapabilityProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityProfile.
func (in *PDUCapabilityProfile) DeepCopy() *PDUCapabilityProfile {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDUCapabilityProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityProfileList) DeepCopyInto(out *PDUCapabilityProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PDUCapabilityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityProfileList.
func (in *PDUCapabilityProfileList) DeepCopy() *PDUCapabilityProfileList {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDUCapabilityProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityProfileSelector) DeepCopyInto(out *PDUCapabilityProfileSelector) {
	*out = *in
	if in.Universal != nil {
		in, out := &in.Universal, &out.Universal
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityProfileSelector.
func (in *PDUCapabilityProfileSelector) DeepCopy() *PDUCapabilityProfileSelector {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityProfileSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityProfileSpec) DeepCopyInto(out *PDUCapabilityProfileSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Outlets.DeepCopyInto(&out.Outlets)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	if in.Quirks != nil {
		in, out := &in.Quirks, &out.Quirks
		*out = make([]CapabilityQuirk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityProfileSpec.
func (in *PDUCapabilityProfileSpec) DeepCopy() *PDUCapabilityProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityProfileStatus) DeepCopyInto(out *PDUCapabilityProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityProfileStatus.
func (in *PDUCapabilityProfileStatus) DeepCopy() *PDUCapabilityProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDUCapabilityTelemetrySpec) DeepCopyInto(out *PDUCapabilityTelemetrySpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDUCapabilityTelemetrySpec.
func (in *PDUCapabilityTelemetrySpec) DeepCopy() *PDUCapabilityTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(PDUCapabilityTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanFeasibilityStatus) DeepCopyInto(out *PlanFeasibilityStatus) {
	*out = *in
	if in.RuntimeSeconds != nil {
		in, out := &in.RuntimeSeconds, &out.RuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ThinGroups != nil {
		in, out := &in.ThinGroups, &out.ThinGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanFeasibilityStatus.
func (in *PlanFeasibilityStatus) DeepCopy() *PlanFeasibilityStatus {
	if in == nil {
		return nil
	}
	out := new(PlanFeasibilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerDiagramExportsStatus) DeepCopyInto(out *PlannerDiagramExportsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerDiagramExportsStatus.
func (in *PlannerDiagramExportsStatus) DeepCopy() *PlannerDiagramExportsStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerDiagramExportsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerExplanationStatus) DeepCopyInto(out *PlannerExplanationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerExplanationStatus.
func (in *PlannerExplanationStatus) DeepCopy() *PlannerExplanationStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerExplanationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerGraphEdgeStatus) DeepCopyInto(out *PlannerGraphEdgeStatus) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]PlannerGraphSourceRefStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerGraphEdgeStatus.
func (in *PlannerGraphEdgeStatus) DeepCopy() *PlannerGraphEdgeStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerGraphEdgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerGraphSourceRefStatus) DeepCopyInto(out *PlannerGraphSourceRefStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerGraphSourceRefStatus.
func (in *PlannerGraphSourceRefStatus) DeepCopy() *PlannerGraphSourceRefStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerGraphSourceRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerGraphStatus) DeepCopyInto(out *PlannerGraphStatus) {
	*out = *in
	if in.Vertices != nil {
		in, out := &in.Vertices, &out.Vertices
		*out = make([]PlannerGraphVertexStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]PlannerGraphEdgeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerGraphStatus.
func (in *PlannerGraphStatus) DeepCopy() *PlannerGraphStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerGraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerGraphVertexStatus) DeepCopyInto(out *PlannerGraphVertexStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(int32)
		**out = **in
	}
	if in.ShutdownTier != nil {
		in, out := &in.ShutdownTier, &out.ShutdownTier
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerGraphVertexStatus.
func (in *PlannerGraphVertexStatus) DeepCopy() *PlannerGraphVertexStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerGraphVertexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHardeningSpec) DeepCopyInto(out *PodHardeningSpec) {
	*out = *in
	if in.ReadOnlyRootFilesystem != nil {
		in, out := &in.ReadOnlyRootFilesystem, &out.ReadOnlyRootFilesystem
		*out = new(bool)
		**out = **in
	}
	if in.RunAsNonRoot != nil {
		in, out := &in.RunAsNonRoot, &out.RunAsNonRoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHardeningSpec.
func (in *PodHardeningSpec) DeepCopy() *PodHardeningSpec {
	if in == nil {
		return nil
	}
	out := new(PodHardeningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerImageSet) DeepCopyInto(out *PowerImageSet) {
	*out = *in
	out.Operator = in.Operator
	out.NUTServer = in.NUTServer
	out.UpsmonAgent = in.UpsmonAgent
	out.Actuator = in.Actuator
	out.Exporter = in.Exporter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerImageSet.
func (in *PowerImageSet) DeepCopy() *PowerImageSet {
	if in == nil {
		return nil
	}
	out := new(PowerImageSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInfrastructure) DeepCopyInto(out *PowerInfrastructure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInfrastructure.
func (in *PowerInfrastructure) DeepCopy() *PowerInfrastructure {
	if in == nil {
		return nil
	}
	out := new(PowerInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerInfrastructure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInfrastructureList) DeepCopyInto(out *PowerInfrastructureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerInfrastructure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInfrastructureList.
func (in *PowerInfrastructureList) DeepCopy() *PowerInfrastructureList {
	if in == nil {
		return nil
	}
	out := new(PowerInfrastructureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerInfrastructureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInfrastructureSpec) DeepCopyInto(out *PowerInfrastructureSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInfrastructureSpec.
func (in *PowerInfrastructureSpec) DeepCopy() *PowerInfrastructureSpec {
	if in == nil {
		return nil
	}
	out := new(PowerInfrastructureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInfrastructureStatus) DeepCopyInto(out *PowerInfrastructureStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInfrastructureStatus.
func (in *PowerInfrastructureStatus) DeepCopy() *PowerInfrastructureStatus {
	if in == nil {
		return nil
	}
	out := new(PowerInfrastructureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryEdge) DeepCopyInto(out *PowerInventoryEdge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryEdge.
func (in *PowerInventoryEdge) DeepCopy() *PowerInventoryEdge {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerInventoryEdge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryEdgeList) DeepCopyInto(out *PowerInventoryEdgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerInventoryEdge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryEdgeList.
func (in *PowerInventoryEdgeList) DeepCopy() *PowerInventoryEdgeList {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryEdgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerInventoryEdgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryEdgeSpec) DeepCopyInto(out *PowerInventoryEdgeSpec) {
	*out = *in
	out.From = in.From
	out.To = in.To
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryEdgeSpec.
func (in *PowerInventoryEdgeSpec) DeepCopy() *PowerInventoryEdgeSpec {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryEdgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryEdgeStatus) DeepCopyInto(out *PowerInventoryEdgeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryEdgeStatus.
func (in *PowerInventoryEdgeStatus) DeepCopy() *PowerInventoryEdgeStatus {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryEdgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryEntityReference) DeepCopyInto(out *PowerInventoryEntityReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryEntityReference.
func (in *PowerInventoryEntityReference) DeepCopy() *PowerInventoryEntityReference {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryEntityReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryNode) DeepCopyInto(out *PowerInventoryNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryNode.
func (in *PowerInventoryNode) DeepCopy() *PowerInventoryNode {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerInventoryNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryNodeList) DeepCopyInto(out *PowerInventoryNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerInventoryNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryNodeList.
func (in *PowerInventoryNodeList) DeepCopy() *PowerInventoryNodeList {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerInventoryNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryNodeRoles) DeepCopyInto(out *PowerInventoryNodeRoles) {
	*out = *in
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(bool)
		**out = **in
	}
	if in.ControlPlaneQuorumMember != nil {
		in, out := &in.ControlPlaneQuorumMember, &out.ControlPlaneQuorumMember
		*out = new(bool)
		**out = **in
	}
	if in.ShutdownTier != nil {
		in, out := &in.ShutdownTier, &out.ShutdownTier
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryNodeRoles.
func (in *PowerInventoryNodeRoles) DeepCopy() *PowerInventoryNodeRoles {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryNodeRoles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryNodeSpec) DeepCopyInto(out *PowerInventoryNodeSpec) {
	*out = *in
	if in.PowerPlanningExempt != nil {
		in, out := &in.PowerPlanningExempt, &out.PowerPlanningExempt
		*out = new(bool)
		**out = **in
	}
	if in.CommunicationPathExempt != nil {
		in, out := &in.CommunicationPathExempt, &out.CommunicationPathExempt
		*out = new(bool)
		**out = **in
	}
	in.Roles.DeepCopyInto(&out.Roles)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryNodeSpec.
func (in *PowerInventoryNodeSpec) DeepCopy() *PowerInventoryNodeSpec {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventoryNodeStatus) DeepCopyInto(out *PowerInventoryNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventoryNodeStatus.
func (in *PowerInventoryNodeStatus) DeepCopy() *PowerInventoryNodeStatus {
	if in == nil {
		return nil
	}
	out := new(PowerInventoryNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerInventorySpec) DeepCopyInto(out *PowerInventorySpec) {
	*out = *in
	if in.SnapshotAgeLevels != nil {
		in, out := &in.SnapshotAgeLevels, &out.SnapshotAgeLevels
		*out = make([]PowerSnapshotAgeLevel, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerInventorySpec.
func (in *PowerInventorySpec) DeepCopy() *PowerInventorySpec {
	if in == nil {
		return nil
	}
	out := new(PowerInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementCluster) DeepCopyInto(out *PowerManagementCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementCluster.
func (in *PowerManagementCluster) DeepCopy() *PowerManagementCluster {
	if in == nil {
		return nil
	}
	out := new(PowerManagementCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerManagementCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementClusterList) DeepCopyInto(out *PowerManagementClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerManagementCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementClusterList.
func (in *PowerManagementClusterList) DeepCopy() *PowerManagementClusterList {
	if in == nil {
		return nil
	}
	out := new(PowerManagementClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerManagementClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementClusterSpec) DeepCopyInto(out *PowerManagementClusterSpec) {
	*out = *in
	if in.OperandNamespace != nil {
		in, out := &in.OperandNamespace, &out.OperandNamespace
		*out = new(OperandNamespaceSpec)
		(*in).DeepCopyInto(*out)
	}
	in.ShutdownTiers.DeepCopyInto(&out.ShutdownTiers)
	in.Inventory.DeepCopyInto(&out.Inventory)
	in.Storage.DeepCopyInto(&out.Storage)
	out.Images = in.Images
	in.Security.DeepCopyInto(&out.Security)
	in.Observability.DeepCopyInto(&out.Observability)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementClusterSpec.
func (in *PowerManagementClusterSpec) DeepCopy() *PowerManagementClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PowerManagementClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementClusterStatus) DeepCopyInto(out *PowerManagementClusterStatus) {
	*out = *in
	out.Storage = in.Storage
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementClusterStatus.
func (in *PowerManagementClusterStatus) DeepCopy() *PowerManagementClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PowerManagementClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerObservabilitySpec) DeepCopyInto(out *PowerObservabilitySpec) {
	*out = *in
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(bool)
		**out = **in
	}
	if in.KubernetesEvents != nil {
		in, out := &in.KubernetesEvents, &out.KubernetesEvents
		*out = new(bool)
		**out = **in
	}
	if in.TelemetryInterval != nil {
		in, out := &in.TelemetryInterval, &out.TelemetryInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PublishCadence != nil {
		in, out := &in.PublishCadence, &out.PublishCadence
		*out = new(PublishCadenceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerObservabilitySpec.
func (in *PowerObservabilitySpec) DeepCopy() *PowerObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(PowerObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSecuritySpec) DeepCopyInto(out *PowerSecuritySpec) {
	*out = *in
	in.DefaultPodHardening.DeepCopyInto(&out.DefaultPodHardening)
	if in.RequireExplicitActuation != nil {
		in, out := &in.RequireExplicitActuation, &out.RequireExplicitActuation
		*out = new(bool)
		**out = **in
	}
	if in.AllowedActuatorNamespaces != nil {
		in, out := &in.AllowedActuatorNamespaces, &out.AllowedActuatorNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSecuritySpec.
func (in *PowerSecuritySpec) DeepCopy() *PowerSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(PowerSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerShutdownTierDefinition) DeepCopyInto(out *PowerShutdownTierDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerShutdownTierDefinition.
func (in *PowerShutdownTierDefinition) DeepCopy() *PowerShutdownTierDefinition {
	if in == nil {
		return nil
	}
	out := new(PowerShutdownTierDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerShutdownTierPolicySpec) DeepCopyInto(out *PowerShutdownTierPolicySpec) {
	*out = *in
	if in.DefaultTier != nil {
		in, out := &in.DefaultTier, &out.DefaultTier
		*out = new(int32)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]PowerShutdownTierDefinition, len(*in))
		copy(*out, *in)
	}
	if in.SelectorRules != nil {
		in, out := &in.SelectorRules, &out.SelectorRules
		*out = make([]PowerShutdownTierSelectorRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerShutdownTierPolicySpec.
func (in *PowerShutdownTierPolicySpec) DeepCopy() *PowerShutdownTierPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PowerShutdownTierPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerShutdownTierSelectorRule) DeepCopyInto(out *PowerShutdownTierSelectorRule) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerShutdownTierSelectorRule.
func (in *PowerShutdownTierSelectorRule) DeepCopy() *PowerShutdownTierSelectorRule {
	if in == nil {
		return nil
	}
	out := new(PowerShutdownTierSelectorRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSnapshotAgeLevel) DeepCopyInto(out *PowerSnapshotAgeLevel) {
	*out = *in
	out.After = in.After
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSnapshotAgeLevel.
func (in *PowerSnapshotAgeLevel) DeepCopy() *PowerSnapshotAgeLevel {
	if in == nil {
		return nil
	}
	out := new(PowerSnapshotAgeLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerStorageSpec) DeepCopyInto(out *PowerStorageSpec) {
	*out = *in
	if in.ExternalPostgres != nil {
		in, out := &in.ExternalPostgres, &out.ExternalPostgres
		*out = new(ExternalPostgresStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CNPG != nil {
		in, out := &in.CNPG, &out.CNPG
		*out = new(CNPGStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.AuditSpool.DeepCopyInto(&out.AuditSpool)
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(AuditRetentionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerStorageSpec.
func (in *PowerStorageSpec) DeepCopy() *PowerStorageSpec {
	if in == nil {
		return nil
	}
	out := new(PowerStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishCadenceSpec) DeepCopyInto(out *PublishCadenceSpec) {
	*out = *in
	if in.Idle != nil {
		in, out := &in.Idle, &out.Idle
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishCadenceSpec.
func (in *PublishCadenceSpec) DeepCopy() *PublishCadenceSpec {
	if in == nil {
		return nil
	}
	out := new(PublishCadenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishedPlannerArtifactStatus) DeepCopyInto(out *PublishedPlannerArtifactStatus) {
	*out = *in
	in.Graph.DeepCopyInto(&out.Graph)
	if in.StartupWaves != nil {
		in, out := &in.StartupWaves, &out.StartupWaves
		*out = make([]CompiledShutdownWave, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Explanations != nil {
		in, out := &in.Explanations, &out.Explanations
		*out = make([]PlannerExplanationStatus, len(*in))
		copy(*out, *in)
	}
	out.Diagrams = in.Diagrams
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishedPlannerArtifactStatus.
func (in *PublishedPlannerArtifactStatus) DeepCopy() *PublishedPlannerArtifactStatus {
	if in == nil {
		return nil
	}
	out := new(PublishedPlannerArtifactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointStatus) DeepCopyInto(out *ServiceEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointStatus.
func (in *ServiceEndpointStatus) DeepCopy() *ServiceEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownExecutionAdaptiveStatus) DeepCopyInto(out *ShutdownExecutionAdaptiveStatus) {
	*out = *in
	if in.RuntimeSeconds != nil {
		in, out := &in.RuntimeSeconds, &out.RuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownExecutionAdaptiveStatus.
func (in *ShutdownExecutionAdaptiveStatus) DeepCopy() *ShutdownExecutionAdaptiveStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownExecutionAdaptiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownExecutionStatus) DeepCopyInto(out *ShutdownExecutionStatus) {
	*out = *in
	if in.SelectedUPSDevices != nil {
		in, out := &in.SelectedUPSDevices, &out.SelectedUPSDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Adaptive != nil {
		in, out := &in.Adaptive, &out.Adaptive
		*out = new(ShutdownExecutionAdaptiveStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownExecutionStatus.
func (in *ShutdownExecutionStatus) DeepCopy() *ShutdownExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlow) DeepCopyInto(out *ShutdownFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlow.
func (in *ShutdownFlow) DeepCopy() *ShutdownFlow {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShutdownFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlowList) DeepCopyInto(out *ShutdownFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShutdownFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlowList.
func (in *ShutdownFlowList) DeepCopy() *ShutdownFlowList {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShutdownFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlowSpec) DeepCopyInto(out *ShutdownFlowSpec) {
	*out = *in
	if in.ManagementClusterRef != nil {
		in, out := &in.ManagementClusterRef, &out.ManagementClusterRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]ShutdownTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]ShutdownGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]ShutdownStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AbortPolicy.DeepCopyInto(&out.AbortPolicy)
	in.Safety.DeepCopyInto(&out.Safety)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlowSpec.
func (in *ShutdownFlowSpec) DeepCopy() *ShutdownFlowSpec {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlowStatus) DeepCopyInto(out *ShutdownFlowStatus) {
	*out = *in
	if in.CompiledSteps != nil {
		in, out := &in.CompiledSteps, &out.CompiledSteps
		*out = make([]CompiledShutdownStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompiledWaves != nil {
		in, out := &in.CompiledWaves, &out.CompiledWaves
		*out = make([]CompiledShutdownWave, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PublishedArtifact != nil {
		in, out := &in.PublishedArtifact, &out.PublishedArtifact
		*out = new(PublishedPlannerArtifactStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockedNodeReleases != nil {
		in, out := &in.BlockedNodeReleases, &out.BlockedNodeReleases
		*out = make([]BlockedNodeReleaseStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EstimatedDuration != nil {
		in, out := &in.EstimatedDuration, &out.EstimatedDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PlanFeasibility != nil {
		in, out := &in.PlanFeasibility, &out.PlanFeasibility
		*out = new(PlanFeasibilityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastEvaluationTime != nil {
		in, out := &in.LastEvaluationTime, &out.LastEvaluationTime
		*out = (*in).DeepCopy()
	}
	if in.LastPublishTime != nil {
		in, out := &in.LastPublishTime, &out.LastPublishTime
		*out = (*in).DeepCopy()
	}
	if in.TriggerEvaluation != nil {
		in, out := &in.TriggerEvaluation, &out.TriggerEvaluation
		*out = new(ShutdownTriggerEvaluationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TriggerHoldStates != nil {
		in, out := &in.TriggerHoldStates, &out.TriggerHoldStates
		*out = make([]ShutdownTriggerHoldStateStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastExecution != nil {
		in, out := &in.LastExecution, &out.LastExecution
		*out = new(ShutdownExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlowStatus.
func (in *ShutdownFlowStatus) DeepCopy() *ShutdownFlowStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownGroup) DeepCopyInto(out *ShutdownGroup) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Before != nil {
		in, out := &in.Before, &out.Before
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(int32)
		**out = **in
	}
	if in.ShutdownTier != nil {
		in, out := &in.ShutdownTier, &out.ShutdownTier
		*out = new(int32)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownGroup.
func (in *ShutdownGroup) DeepCopy() *ShutdownGroup {
	if in == nil {
		return nil
	}
	out := new(ShutdownGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownStep) DeepCopyInto(out *ShutdownStep) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ContinueOnError != nil {
		in, out := &in.ContinueOnError, &out.ContinueOnError
		*out = new(bool)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownStep.
func (in *ShutdownStep) DeepCopy() *ShutdownStep {
	if in == nil {
		return nil
	}
	out := new(ShutdownStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownStepTarget) DeepCopyInto(out *ShutdownStepTarget) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadRefs != nil {
		in, out := &in.WorkloadRefs, &out.WorkloadRefs
		*out = make([]WorkloadReference, len(*in))
		copy(*out, *in)
	}
	if in.AgentRefs != nil {
		in, out := &in.AgentRefs, &out.AgentRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownStepTarget.
func (in *ShutdownStepTarget) DeepCopy() *ShutdownStepTarget {
	if in == nil {
		return nil
	}
	out := new(ShutdownStepTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownTrigger) DeepCopyInto(out *ShutdownTrigger) {
	*out = *in
	if in.FallbackType != nil {
		in, out := &in.FallbackType, &out.FallbackType
		*out = new(ShutdownTriggerType)
		**out = **in
	}
	if in.UPSDeviceRefs != nil {
		in, out := &in.UPSDeviceRefs, &out.UPSDeviceRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
	if in.PowerDomains != nil {
		in, out := &in.PowerDomains, &out.PowerDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RuntimeBelowSeconds != nil {
		in, out := &in.RuntimeBelowSeconds, &out.RuntimeBelowSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ChargeBelowPercent != nil {
		in, out := &in.ChargeBelowPercent, &out.ChargeBelowPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownTrigger.
func (in *ShutdownTrigger) DeepCopy() *ShutdownTrigger {
	if in == nil {
		return nil
	}
	out := new(ShutdownTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownTriggerDecisionStatus) DeepCopyInto(out *ShutdownTriggerDecisionStatus) {
	*out = *in
	if in.SelectedUPSDevices != nil {
		in, out := &in.SelectedUPSDevices, &out.SelectedUPSDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HoldStartedAt != nil {
		in, out := &in.HoldStartedAt, &out.HoldStartedAt
		*out = (*in).DeepCopy()
	}
	if in.EligibleAt != nil {
		in, out := &in.EligibleAt, &out.EligibleAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownTriggerDecisionStatus.
func (in *ShutdownTriggerDecisionStatus) DeepCopy() *ShutdownTriggerDecisionStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownTriggerDecisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownTriggerDiagnosticStatus) DeepCopyInto(out *ShutdownTriggerDiagnosticStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownTriggerDiagnosticStatus.
func (in *ShutdownTriggerDiagnosticStatus) DeepCopy() *ShutdownTriggerDiagnosticStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownTriggerDiagnosticStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownTriggerEvaluationStatus) DeepCopyInto(out *ShutdownTriggerEvaluationStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.SelectedUPSDevices != nil {
		in, out := &in.SelectedUPSDevices, &out.SelectedUPSDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Decisions != nil {
		in, out := &in.Decisions, &out.Decisions
		*out = make([]ShutdownTriggerDecisionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Diagnostics != nil {
		in, out := &in.Diagnostics, &out.Diagnostics
		*out = make([]ShutdownTriggerDiagnosticStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownTriggerEvaluationStatus.
func (in *ShutdownTriggerEvaluationStatus) DeepCopy() *ShutdownTriggerEvaluationStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownTriggerEvaluationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownTriggerHoldStateStatus) DeepCopyInto(out *ShutdownTriggerHoldStateStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownTriggerHoldStateStatus.
func (in *ShutdownTriggerHoldStateStatus) DeepCopy() *ShutdownTriggerHoldStateStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownTriggerHoldStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageStatus) DeepCopyInto(out *StorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageStatus.
func (in *StorageStatus) DeepCopy() *StorageStatus {
	if in == nil {
		return nil
	}
	out := new(StorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityActuationSpec) DeepCopyInto(out *UPSCapabilityActuationSpec) {
	*out = *in
	if in.Behaviors != nil {
		in, out := &in.Behaviors, &out.Behaviors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityActuationSpec.
func (in *UPSCapabilityActuationSpec) DeepCopy() *UPSCapabilityActuationSpec {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityActuationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbe) DeepCopyInto(out *UPSCapabilityProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbe.
func (in *UPSCapabilityProbe) DeepCopy() *UPSCapabilityProbe {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSCapabilityProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbeDeviceReference) DeepCopyInto(out *UPSCapabilityProbeDeviceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbeDeviceReference.
func (in *UPSCapabilityProbeDeviceReference) DeepCopy() *UPSCapabilityProbeDeviceReference {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbeDeviceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbeIdentity) DeepCopyInto(out *UPSCapabilityProbeIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbeIdentity.
func (in *UPSCapabilityProbeIdentity) DeepCopy() *UPSCapabilityProbeIdentity {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbeIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbeList) DeepCopyInto(out *UPSCapabilityProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UPSCapabilityProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbeList.
func (in *UPSCapabilityProbeList) DeepCopy() *UPSCapabilityProbeList {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSCapabilityProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbeMatch) DeepCopyInto(out *UPSCapabilityProbeMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbeMatch.
func (in *UPSCapabilityProbeMatch) DeepCopy() *UPSCapabilityProbeMatch {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbeMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbeSpec) DeepCopyInto(out *UPSCapabilityProbeSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbeSpec.
func (in *UPSCapabilityProbeSpec) DeepCopy() *UPSCapabilityProbeSpec {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProbeStatus) DeepCopyInto(out *UPSCapabilityProbeStatus) {
	*out = *in
	if in.ProbedAt != nil {
		in, out := &in.ProbedAt, &out.ProbedAt
		*out = (*in).DeepCopy()
	}
	out.Identity = in.Identity
	if in.ReportedVariables != nil {
		in, out := &in.ReportedVariables, &out.ReportedVariables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NonStandardVariables != nil {
		in, out := &in.NonStandardVariables, &out.NonStandardVariables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SuggestedAliases != nil {
		in, out := &in.SuggestedAliases, &out.SuggestedAliases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.CurrentMatch = in.CurrentMatch
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProbeStatus.
func (in *UPSCapabilityProbeStatus) DeepCopy() *UPSCapabilityProbeStatus {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProfile) DeepCopyInto(out *UPSCapabilityProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProfile.
func (in *UPSCapabilityProfile) DeepCopy() *UPSCapabilityProfile {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSCapabilityProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProfileList) DeepCopyInto(out *UPSCapabilityProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UPSCapabilityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProfileList.
func (in *UPSCapabilityProfileList) DeepCopy() *UPSCapabilityProfileList {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSCapabilityProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProfileSelector) DeepCopyInto(out *UPSCapabilityProfileSelector) {
	*out = *in
	if in.Universal != nil {
		in, out := &in.Universal, &out.Universal
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProfileSelector.
func (in *UPSCapabilityProfileSelector) DeepCopy() *UPSCapabilityProfileSelector {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProfileSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProfileSpec) DeepCopyInto(out *UPSCapabilityProfileSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	in.Actuation.DeepCopyInto(&out.Actuation)
	if in.Quirks != nil {
		in, out := &in.Quirks, &out.Quirks
		*out = make([]CapabilityQuirk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProfileSpec.
func (in *UPSCapabilityProfileSpec) DeepCopy() *UPSCapabilityProfileSpec {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityProfileStatus) DeepCopyInto(out *UPSCapabilityProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityProfileStatus.
func (in *UPSCapabilityProfileStatus) DeepCopy() *UPSCapabilityProfileStatus {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSCapabilityTelemetrySpec) DeepCopyInto(out *UPSCapabilityTelemetrySpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSCapabilityTelemetrySpec.
func (in *UPSCapabilityTelemetrySpec) DeepCopy() *UPSCapabilityTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(UPSCapabilityTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDevice) DeepCopyInto(out *UPSDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDevice.
func (in *UPSDevice) DeepCopy() *UPSDevice {
	if in == nil {
		return nil
	}
	out := new(UPSDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceCapabilityStatus) DeepCopyInto(out *UPSDeviceCapabilityStatus) {
	*out = *in
	if in.Quirks != nil {
		in, out := &in.Quirks, &out.Quirks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActuationBehaviors != nil {
		in, out := &in.ActuationBehaviors, &out.ActuationBehaviors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceCapabilityStatus.
func (in *UPSDeviceCapabilityStatus) DeepCopy() *UPSDeviceCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceIdentitySpec) DeepCopyInto(out *UPSDeviceIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceIdentitySpec.
func (in *UPSDeviceIdentitySpec) DeepCopy() *UPSDeviceIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceList) DeepCopyInto(out *UPSDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UPSDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceList.
func (in *UPSDeviceList) DeepCopy() *UPSDeviceList {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceSimulation) DeepCopyInto(out *UPSDeviceSimulation) {
	*out = *in
	out.SequenceConfigMapRef = in.SequenceConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceSimulation.
func (in *UPSDeviceSimulation) DeepCopy() *UPSDeviceSimulation {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceSimulation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceSpec) DeepCopyInto(out *UPSDeviceSpec) {
	*out = *in
	out.Identity = in.Identity
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(UPSEndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.UpstreamNUT != nil {
		in, out := &in.UpstreamNUT, &out.UpstreamNUT
		*out = new(UPSUpstreamNUTSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.DriverOptions != nil {
		in, out := &in.DriverOptions, &out.DriverOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PowerDomains != nil {
		in, out := &in.PowerDomains, &out.PowerDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	if in.Simulation != nil {
		in, out := &in.Simulation, &out.Simulation
		*out = new(UPSDeviceSimulation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceSpec.
func (in *UPSDeviceSpec) DeepCopy() *UPSDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceStatus) DeepCopyInto(out *UPSDeviceStatus) {
	*out = *in
	if in.ServerRefs != nil {
		in, out := &in.ServerRefs, &out.ServerRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.BatteryChargePercent != nil {
		in, out := &in.BatteryChargePercent, &out.BatteryChargePercent
		*out = new(int32)
		**out = **in
	}
	if in.RuntimeSeconds != nil {
		in, out := &in.RuntimeSeconds, &out.RuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.LoadPercent != nil {
		in, out := &in.LoadPercent, &out.LoadPercent
		*out = new(int32)
		**out = **in
	}
	if in.Capability != nil {
		in, out := &in.Capability, &out.Capability
		*out = new(UPSDeviceCapabilityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceStatus.
func (in *UPSDeviceStatus) DeepCopy() *UPSDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSEndpointSpec) DeepCopyInto(out *UPSEndpointSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSEndpointSpec.
func (in *UPSEndpointSpec) DeepCopy() *UPSEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(UPSEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSTelemetrySpec) DeepCopyInto(out *UPSTelemetrySpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AlertPollInterval != nil {
		in, out := &in.AlertPollInterval, &out.AlertPollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSTelemetrySpec.
func (in *UPSTelemetrySpec) DeepCopy() *UPSTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(UPSTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSThresholdsSpec) DeepCopyInto(out *UPSThresholdsSpec) {
	*out = *in
	if in.MinRuntimeSeconds != nil {
		in, out := &in.MinRuntimeSeconds, &out.MinRuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MinChargePercent != nil {
		in, out := &in.MinChargePercent, &out.MinChargePercent
		*out = new(int32)
		**out = **in
	}
	if in.OnBatteryHoldoff != nil {
		in, out := &in.OnBatteryHoldoff, &out.OnBatteryHoldoff
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.StaleAfter != nil {
		in, out := &in.StaleAfter, &out.StaleAfter
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSThresholdsSpec.
func (in *UPSThresholdsSpec) DeepCopy() *UPSThresholdsSpec {
	if in == nil {
		return nil
	}
	out := new(UPSThresholdsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSUpstreamNUTAuthSpec) DeepCopyInto(out *UPSUpstreamNUTAuthSpec) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSUpstreamNUTAuthSpec.
func (in *UPSUpstreamNUTAuthSpec) DeepCopy() *UPSUpstreamNUTAuthSpec {
	if in == nil {
		return nil
	}
	out := new(UPSUpstreamNUTAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSUpstreamNUTSpec) DeepCopyInto(out *UPSUpstreamNUTSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.StrictStart != nil {
		in, out := &in.StrictStart, &out.StrictStart
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSUpstreamNUTSpec.
func (in *UPSUpstreamNUTSpec) DeepCopy() *UPSUpstreamNUTSpec {
	if in == nil {
		return nil
	}
	out := new(UPSUpstreamNUTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpsmonConfigSpec) DeepCopyInto(out *UpsmonConfigSpec) {
	*out = *in
	if in.PollFrequency != nil {
		in, out := &in.PollFrequency, &out.PollFrequency
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AlertPollFrequency != nil {
		in, out := &in.AlertPollFrequency, &out.AlertPollFrequency
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DeadTime != nil {
		in, out := &in.DeadTime, &out.DeadTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HostSync != nil {
		in, out := &in.HostSync, &out.HostSync
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FinalDelay != nil {
		in, out := &in.FinalDelay, &out.FinalDelay
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpsmonConfigSpec.
func (in *UpsmonConfigSpec) DeepCopy() *UpsmonConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UpsmonConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPlacementSpec) DeepCopyInto(out *WorkloadPlacementSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPlacementSpec.
func (in *WorkloadPlacementSpec) DeepCopy() *WorkloadPlacementSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadPlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
