//go:build !ignore_autogenerated

/*
Copyright 2026 Michael Zalud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbortPolicySpec) DeepCopyInto(out *AbortPolicySpec) {
	*out = *in
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbortPolicySpec.
func (in *AbortPolicySpec) DeepCopy() *AbortPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AbortPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentShutdownSpec) DeepCopyInto(out *AgentShutdownSpec) {
	*out = *in
	if in.SignalTTL != nil {
		in, out := &in.SignalTTL, &out.SignalTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RequireFreshTelemetry != nil {
		in, out := &in.RequireFreshTelemetry, &out.RequireFreshTelemetry
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentShutdownSpec.
func (in *AgentShutdownSpec) DeepCopy() *AgentShutdownSpec {
	if in == nil {
		return nil
	}
	out := new(AgentShutdownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRetentionSpec) DeepCopyInto(out *AuditRetentionSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRetentionSpec.
func (in *AuditRetentionSpec) DeepCopy() *AuditRetentionSpec {
	if in == nil {
		return nil
	}
	out := new(AuditRetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGStorageSpec) DeepCopyInto(out *CNPGStorageSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.AppCredentialSecretRef != nil {
		in, out := &in.AppCredentialSecretRef, &out.AppCredentialSecretRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGStorageSpec.
func (in *CNPGStorageSpec) DeepCopy() *CNPGStorageSpec {
	if in == nil {
		return nil
	}
	out := new(CNPGStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShutdownStep) DeepCopyInto(out *CompiledShutdownStep) {
	*out = *in
	if in.CumulativeDuration != nil {
		in, out := &in.CumulativeDuration, &out.CumulativeDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShutdownStep.
func (in *CompiledShutdownStep) DeepCopy() *CompiledShutdownStep {
	if in == nil {
		return nil
	}
	out := new(CompiledShutdownStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompiledShutdownWave) DeepCopyInto(out *CompiledShutdownWave) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(int32)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CumulativeDuration != nil {
		in, out := &in.CumulativeDuration, &out.CumulativeDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompiledShutdownWave.
func (in *CompiledShutdownWave) DeepCopy() *CompiledShutdownWave {
	if in == nil {
		return nil
	}
	out := new(CompiledShutdownWave)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPostgresStorageSpec) DeepCopyInto(out *ExternalPostgresStorageSpec) {
	*out = *in
	out.DSNSecretKeyRef = in.DSNSecretKeyRef
	if in.RequireTLS != nil {
		in, out := &in.RequireTLS, &out.RequireTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPostgresStorageSpec.
func (in *ExternalPostgresStorageSpec) DeepCopy() *ExternalPostgresStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalPostgresStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowSafetySpec) DeepCopyInto(out *FlowSafetySpec) {
	*out = *in
	if in.RequireManualApproval != nil {
		in, out := &in.RequireManualApproval, &out.RequireManualApproval
		*out = new(bool)
		**out = **in
	}
	if in.MaxEstimatedDuration != nil {
		in, out := &in.MaxEstimatedDuration, &out.MaxEstimatedDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowSafetySpec.
func (in *FlowSafetySpec) DeepCopy() *FlowSafetySpec {
	if in == nil {
		return nil
	}
	out := new(FlowSafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageReference) DeepCopyInto(out *ImageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReference.
func (in *ImageReference) DeepCopy() *ImageReference {
	if in == nil {
		return nil
	}
	out := new(ImageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResourceStatus) DeepCopyInto(out *ManagedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResourceStatus.
func (in *ManagedResourceStatus) DeepCopy() *ManagedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTAuthSpec) DeepCopyInto(out *NUTAuthSpec) {
	*out = *in
	if in.ExistingSecretRef != nil {
		in, out := &in.ExistingSecretRef, &out.ExistingSecretRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.PerNodeUsers != nil {
		in, out := &in.PerNodeUsers, &out.PerNodeUsers
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTAuthSpec.
func (in *NUTAuthSpec) DeepCopy() *NUTAuthSpec {
	if in == nil {
		return nil
	}
	out := new(NUTAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServer) DeepCopyInto(out *NUTServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServer.
func (in *NUTServer) DeepCopy() *NUTServer {
	if in == nil {
		return nil
	}
	out := new(NUTServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NUTServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerConfigSpec) DeepCopyInto(out *NUTServerConfigSpec) {
	*out = *in
	if in.MaxStartDelay != nil {
		in, out := &in.MaxStartDelay, &out.MaxStartDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerConfigSpec.
func (in *NUTServerConfigSpec) DeepCopy() *NUTServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NUTServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerList) DeepCopyInto(out *NUTServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NUTServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerList.
func (in *NUTServerList) DeepCopy() *NUTServerList {
	if in == nil {
		return nil
	}
	out := new(NUTServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NUTServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerSpec) DeepCopyInto(out *NUTServerSpec) {
	*out = *in
	if in.ManagementClusterRef != nil {
		in, out := &in.ManagementClusterRef, &out.ManagementClusterRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	if in.DeviceRefs != nil {
		in, out := &in.DeviceRefs, &out.DeviceRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
	if in.DeviceSelector != nil {
		in, out := &in.DeviceSelector, &out.DeviceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Image = in.Image
	in.Placement.DeepCopyInto(&out.Placement)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Service.DeepCopyInto(&out.Service)
	in.Auth.DeepCopyInto(&out.Auth)
	in.TLS.DeepCopyInto(&out.TLS)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerSpec.
func (in *NUTServerSpec) DeepCopy() *NUTServerSpec {
	if in == nil {
		return nil
	}
	out := new(NUTServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServerStatus) DeepCopyInto(out *NUTServerStatus) {
	*out = *in
	if in.SelectedDevices != nil {
		in, out := &in.SelectedDevices, &out.SelectedDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceEndpoints != nil {
		in, out := &in.ServiceEndpoints, &out.ServiceEndpoints
		*out = make([]ServiceEndpointStatus, len(*in))
		copy(*out, *in)
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServerStatus.
func (in *NUTServerStatus) DeepCopy() *NUTServerStatus {
	if in == nil {
		return nil
	}
	out := new(NUTServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTServiceSpec) DeepCopyInto(out *NUTServiceSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTServiceSpec.
func (in *NUTServiceSpec) DeepCopy() *NUTServiceSpec {
	if in == nil {
		return nil
	}
	out := new(NUTServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUTTLSSpec) DeepCopyInto(out *NUTTLSSpec) {
	*out = *in
	if in.ServerCertificateRef != nil {
		in, out := &in.ServerCertificateRef, &out.ServerCertificateRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.ClientCARef != nil {
		in, out := &in.ClientCARef, &out.ClientCARef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.VerifyClientCertificates != nil {
		in, out := &in.VerifyClientCertificates, &out.VerifyClientCertificates
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUTTLSSpec.
func (in *NUTTLSSpec) DeepCopy() *NUTTLSSpec {
	if in == nil {
		return nil
	}
	out := new(NUTTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedNameReference) DeepCopyInto(out *NamespacedNameReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedNameReference.
func (in *NamespacedNameReference) DeepCopy() *NamespacedNameReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedNameReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgent) DeepCopyInto(out *NodePowerAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgent.
func (in *NodePowerAgent) DeepCopy() *NodePowerAgent {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePowerAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentImages) DeepCopyInto(out *NodePowerAgentImages) {
	*out = *in
	out.Upsmon = in.Upsmon
	out.Actuator = in.Actuator
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentImages.
func (in *NodePowerAgentImages) DeepCopy() *NodePowerAgentImages {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentList) DeepCopyInto(out *NodePowerAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePowerAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentList.
func (in *NodePowerAgentList) DeepCopy() *NodePowerAgentList {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePowerAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentResources) DeepCopyInto(out *NodePowerAgentResources) {
	*out = *in
	in.Upsmon.DeepCopyInto(&out.Upsmon)
	in.Actuator.DeepCopyInto(&out.Actuator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentResources.
func (in *NodePowerAgentResources) DeepCopy() *NodePowerAgentResources {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentSpec) DeepCopyInto(out *NodePowerAgentSpec) {
	*out = *in
	if in.ManagementClusterRef != nil {
		in, out := &in.ManagementClusterRef, &out.ManagementClusterRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	if in.NUTServerRefs != nil {
		in, out := &in.NUTServerRefs, &out.NUTServerRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ShutdownFlowRef != nil {
		in, out := &in.ShutdownFlowRef, &out.ShutdownFlowRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	out.Images = in.Images
	in.Placement.DeepCopyInto(&out.Placement)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Upsmon.DeepCopyInto(&out.Upsmon)
	in.Shutdown.DeepCopyInto(&out.Shutdown)
	in.Hardening.DeepCopyInto(&out.Hardening)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentSpec.
func (in *NodePowerAgentSpec) DeepCopy() *NodePowerAgentSpec {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePowerAgentStatus) DeepCopyInto(out *NodePowerAgentStatus) {
	*out = *in
	if in.SelectedNodes != nil {
		in, out := &in.SelectedNodes, &out.SelectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePowerAgentStatus.
func (in *NodePowerAgentStatus) DeepCopy() *NodePowerAgentStatus {
	if in == nil {
		return nil
	}
	out := new(NodePowerAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectNameReference) DeepCopyInto(out *ObjectNameReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectNameReference.
func (in *ObjectNameReference) DeepCopy() *ObjectNameReference {
	if in == nil {
		return nil
	}
	out := new(ObjectNameReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandNamespaceSpec) DeepCopyInto(out *OperandNamespaceSpec) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandNamespaceSpec.
func (in *OperandNamespaceSpec) DeepCopy() *OperandNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(OperandNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHardeningSpec) DeepCopyInto(out *PodHardeningSpec) {
	*out = *in
	if in.ReadOnlyRootFilesystem != nil {
		in, out := &in.ReadOnlyRootFilesystem, &out.ReadOnlyRootFilesystem
		*out = new(bool)
		**out = **in
	}
	if in.RunAsNonRoot != nil {
		in, out := &in.RunAsNonRoot, &out.RunAsNonRoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHardeningSpec.
func (in *PodHardeningSpec) DeepCopy() *PodHardeningSpec {
	if in == nil {
		return nil
	}
	out := new(PodHardeningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerImageSet) DeepCopyInto(out *PowerImageSet) {
	*out = *in
	out.Operator = in.Operator
	out.NUTServer = in.NUTServer
	out.UpsmonAgent = in.UpsmonAgent
	out.Actuator = in.Actuator
	out.Exporter = in.Exporter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerImageSet.
func (in *PowerImageSet) DeepCopy() *PowerImageSet {
	if in == nil {
		return nil
	}
	out := new(PowerImageSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementCluster) DeepCopyInto(out *PowerManagementCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementCluster.
func (in *PowerManagementCluster) DeepCopy() *PowerManagementCluster {
	if in == nil {
		return nil
	}
	out := new(PowerManagementCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerManagementCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementClusterList) DeepCopyInto(out *PowerManagementClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PowerManagementCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementClusterList.
func (in *PowerManagementClusterList) DeepCopy() *PowerManagementClusterList {
	if in == nil {
		return nil
	}
	out := new(PowerManagementClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PowerManagementClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementClusterSpec) DeepCopyInto(out *PowerManagementClusterSpec) {
	*out = *in
	if in.OperandNamespace != nil {
		in, out := &in.OperandNamespace, &out.OperandNamespace
		*out = new(OperandNamespaceSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	out.Images = in.Images
	in.Security.DeepCopyInto(&out.Security)
	in.Observability.DeepCopyInto(&out.Observability)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementClusterSpec.
func (in *PowerManagementClusterSpec) DeepCopy() *PowerManagementClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PowerManagementClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerManagementClusterStatus) DeepCopyInto(out *PowerManagementClusterStatus) {
	*out = *in
	out.Storage = in.Storage
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerManagementClusterStatus.
func (in *PowerManagementClusterStatus) DeepCopy() *PowerManagementClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PowerManagementClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerObservabilitySpec) DeepCopyInto(out *PowerObservabilitySpec) {
	*out = *in
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(bool)
		**out = **in
	}
	if in.KubernetesEvents != nil {
		in, out := &in.KubernetesEvents, &out.KubernetesEvents
		*out = new(bool)
		**out = **in
	}
	if in.TelemetryInterval != nil {
		in, out := &in.TelemetryInterval, &out.TelemetryInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerObservabilitySpec.
func (in *PowerObservabilitySpec) DeepCopy() *PowerObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(PowerObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSecuritySpec) DeepCopyInto(out *PowerSecuritySpec) {
	*out = *in
	in.DefaultPodHardening.DeepCopyInto(&out.DefaultPodHardening)
	if in.RequireExplicitActuation != nil {
		in, out := &in.RequireExplicitActuation, &out.RequireExplicitActuation
		*out = new(bool)
		**out = **in
	}
	if in.AllowedActuatorNamespaces != nil {
		in, out := &in.AllowedActuatorNamespaces, &out.AllowedActuatorNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSecuritySpec.
func (in *PowerSecuritySpec) DeepCopy() *PowerSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(PowerSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerStorageSpec) DeepCopyInto(out *PowerStorageSpec) {
	*out = *in
	if in.ExternalPostgres != nil {
		in, out := &in.ExternalPostgres, &out.ExternalPostgres
		*out = new(ExternalPostgresStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CNPG != nil {
		in, out := &in.CNPG, &out.CNPG
		*out = new(CNPGStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(AuditRetentionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerStorageSpec.
func (in *PowerStorageSpec) DeepCopy() *PowerStorageSpec {
	if in == nil {
		return nil
	}
	out := new(PowerStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointStatus) DeepCopyInto(out *ServiceEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointStatus.
func (in *ServiceEndpointStatus) DeepCopy() *ServiceEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlow) DeepCopyInto(out *ShutdownFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlow.
func (in *ShutdownFlow) DeepCopy() *ShutdownFlow {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShutdownFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlowList) DeepCopyInto(out *ShutdownFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShutdownFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlowList.
func (in *ShutdownFlowList) DeepCopy() *ShutdownFlowList {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShutdownFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlowSpec) DeepCopyInto(out *ShutdownFlowSpec) {
	*out = *in
	if in.ManagementClusterRef != nil {
		in, out := &in.ManagementClusterRef, &out.ManagementClusterRef
		*out = new(ObjectNameReference)
		**out = **in
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]ShutdownTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]ShutdownGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]ShutdownStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AbortPolicy.DeepCopyInto(&out.AbortPolicy)
	in.Safety.DeepCopyInto(&out.Safety)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlowSpec.
func (in *ShutdownFlowSpec) DeepCopy() *ShutdownFlowSpec {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownFlowStatus) DeepCopyInto(out *ShutdownFlowStatus) {
	*out = *in
	if in.CompiledSteps != nil {
		in, out := &in.CompiledSteps, &out.CompiledSteps
		*out = make([]CompiledShutdownStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompiledWaves != nil {
		in, out := &in.CompiledWaves, &out.CompiledWaves
		*out = make([]CompiledShutdownWave, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EstimatedDuration != nil {
		in, out := &in.EstimatedDuration, &out.EstimatedDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LastEvaluationTime != nil {
		in, out := &in.LastEvaluationTime, &out.LastEvaluationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownFlowStatus.
func (in *ShutdownFlowStatus) DeepCopy() *ShutdownFlowStatus {
	if in == nil {
		return nil
	}
	out := new(ShutdownFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownGroup) DeepCopyInto(out *ShutdownGroup) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Before != nil {
		in, out := &in.Before, &out.Before
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(int32)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownGroup.
func (in *ShutdownGroup) DeepCopy() *ShutdownGroup {
	if in == nil {
		return nil
	}
	out := new(ShutdownGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownStep) DeepCopyInto(out *ShutdownStep) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ContinueOnError != nil {
		in, out := &in.ContinueOnError, &out.ContinueOnError
		*out = new(bool)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownStep.
func (in *ShutdownStep) DeepCopy() *ShutdownStep {
	if in == nil {
		return nil
	}
	out := new(ShutdownStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownStepTarget) DeepCopyInto(out *ShutdownStepTarget) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadRefs != nil {
		in, out := &in.WorkloadRefs, &out.WorkloadRefs
		*out = make([]WorkloadReference, len(*in))
		copy(*out, *in)
	}
	if in.AgentRefs != nil {
		in, out := &in.AgentRefs, &out.AgentRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownStepTarget.
func (in *ShutdownStepTarget) DeepCopy() *ShutdownStepTarget {
	if in == nil {
		return nil
	}
	out := new(ShutdownStepTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownTrigger) DeepCopyInto(out *ShutdownTrigger) {
	*out = *in
	if in.UPSDeviceRefs != nil {
		in, out := &in.UPSDeviceRefs, &out.UPSDeviceRefs
		*out = make([]ObjectNameReference, len(*in))
		copy(*out, *in)
	}
	if in.PowerDomains != nil {
		in, out := &in.PowerDomains, &out.PowerDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RuntimeBelowSeconds != nil {
		in, out := &in.RuntimeBelowSeconds, &out.RuntimeBelowSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ChargeBelowPercent != nil {
		in, out := &in.ChargeBelowPercent, &out.ChargeBelowPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownTrigger.
func (in *ShutdownTrigger) DeepCopy() *ShutdownTrigger {
	if in == nil {
		return nil
	}
	out := new(ShutdownTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageStatus) DeepCopyInto(out *StorageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageStatus.
func (in *StorageStatus) DeepCopy() *StorageStatus {
	if in == nil {
		return nil
	}
	out := new(StorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDevice) DeepCopyInto(out *UPSDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDevice.
func (in *UPSDevice) DeepCopy() *UPSDevice {
	if in == nil {
		return nil
	}
	out := new(UPSDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceList) DeepCopyInto(out *UPSDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UPSDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceList.
func (in *UPSDeviceList) DeepCopy() *UPSDeviceList {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPSDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceSpec) DeepCopyInto(out *UPSDeviceSpec) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(UPSEndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(NamespacedNameReference)
		**out = **in
	}
	if in.DriverOptions != nil {
		in, out := &in.DriverOptions, &out.DriverOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PowerDomains != nil {
		in, out := &in.PowerDomains, &out.PowerDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceSpec.
func (in *UPSDeviceSpec) DeepCopy() *UPSDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSDeviceStatus) DeepCopyInto(out *UPSDeviceStatus) {
	*out = *in
	if in.ServerRefs != nil {
		in, out := &in.ServerRefs, &out.ServerRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.BatteryChargePercent != nil {
		in, out := &in.BatteryChargePercent, &out.BatteryChargePercent
		*out = new(int32)
		**out = **in
	}
	if in.RuntimeSeconds != nil {
		in, out := &in.RuntimeSeconds, &out.RuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.LoadPercent != nil {
		in, out := &in.LoadPercent, &out.LoadPercent
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSDeviceStatus.
func (in *UPSDeviceStatus) DeepCopy() *UPSDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(UPSDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSEndpointSpec) DeepCopyInto(out *UPSEndpointSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSEndpointSpec.
func (in *UPSEndpointSpec) DeepCopy() *UPSEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(UPSEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSTelemetrySpec) DeepCopyInto(out *UPSTelemetrySpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AlertPollInterval != nil {
		in, out := &in.AlertPollInterval, &out.AlertPollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSTelemetrySpec.
func (in *UPSTelemetrySpec) DeepCopy() *UPSTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(UPSTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPSThresholdsSpec) DeepCopyInto(out *UPSThresholdsSpec) {
	*out = *in
	if in.MinRuntimeSeconds != nil {
		in, out := &in.MinRuntimeSeconds, &out.MinRuntimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MinChargePercent != nil {
		in, out := &in.MinChargePercent, &out.MinChargePercent
		*out = new(int32)
		**out = **in
	}
	if in.OnBatteryHoldoff != nil {
		in, out := &in.OnBatteryHoldoff, &out.OnBatteryHoldoff
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.StaleAfter != nil {
		in, out := &in.StaleAfter, &out.StaleAfter
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPSThresholdsSpec.
func (in *UPSThresholdsSpec) DeepCopy() *UPSThresholdsSpec {
	if in == nil {
		return nil
	}
	out := new(UPSThresholdsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpsmonConfigSpec) DeepCopyInto(out *UpsmonConfigSpec) {
	*out = *in
	if in.PollFrequency != nil {
		in, out := &in.PollFrequency, &out.PollFrequency
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AlertPollFrequency != nil {
		in, out := &in.AlertPollFrequency, &out.AlertPollFrequency
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DeadTime != nil {
		in, out := &in.DeadTime, &out.DeadTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HostSync != nil {
		in, out := &in.HostSync, &out.HostSync
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FinalDelay != nil {
		in, out := &in.FinalDelay, &out.FinalDelay
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpsmonConfigSpec.
func (in *UpsmonConfigSpec) DeepCopy() *UpsmonConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UpsmonConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPlacementSpec) DeepCopyInto(out *WorkloadPlacementSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPlacementSpec.
func (in *WorkloadPlacementSpec) DeepCopy() *WorkloadPlacementSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadPlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
