name: Tests

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Cache local build tools
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: bin
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile', '.custom-gcl.yml') }}

      - name: Verify go.mod/go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Running Tests
        run: make test
